/**
 * Shared Charts Table Migration
 *
 * Supports the ChartSharingService with persistent storage for
 * chart sharing links, optional password protection, and access tracking.
 */

import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.schema.createTable('shared_charts', (table) => {
    // Primary key
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));

    // Foreign key to charts table
    table.uuid('chart_id').notNullable().references('id').inTable('charts').onDelete('CASCADE');

    // Share token (URL-safe, generated by crypto.randomBytes)
    table.string('share_token').unique().notNullable();

    // Optional password protection (bcrypt hash)
    table.string('password_hash').nullable();

    // Expiration
    table.timestamp('expires_at').notNullable();

    // Creator reference
    table.uuid('created_by').notNullable().references('id').inTable('users').onDelete('CASCADE');

    // Access tracking
    table.integer('access_count').defaultTo(0).notNullable();
    table.timestamp('last_accessed_at').nullable();

    // Timestamps
    table.timestamp('created_at').defaultTo(knex.fn.now()).notNullable();
    table.timestamp('updated_at').defaultTo(knex.fn.now()).notNullable();

    // Indexes for common queries
    table.index(['share_token']);
    table.index(['chart_id']);
    table.index(['created_by']);
    table.index(['expires_at']);
  });
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.dropTableIfExists('shared_charts');
}
